'use client'
import Link from 'next/link'
import { useEffect,useState } from 'react'
import { createClient } from '@/lib/supabase-browser'
import { getCurrentProfile } from '@/lib/auth'
import type { Agent } from '@/lib/types'
import Loading from '@/components/Loading'

export default function SuperadminDashboard(){const[profile,setProfile]=useState<Agent|null>(null);const[counts,setCounts]=useState({agents:0,customers:0,pre:0,visits:0});const[error,setError]=useState('');useEffect(()=>{(async()=>{try{const p=await getCurrentProfile();if(p.role!=='superadmin')return window.location.replace(p.role==='admin'?'/admin':'/agent');setProfile(p);const s=createClient();const[{count:agents},{count:customers},{count:pre},{count:visits}]=await Promise.all([s.from('agents').select('*',{count:'exact',head:true}),s.from('customers').select('*',{count:'exact',head:true}),s.from('pre_visits').select('*',{count:'exact',head:true}),s.from('visits').select('*',{count:'exact',head:true})]);setCounts({agents:agents||0,customers:customers||0,pre:pre||0,visits:visits||0})}catch(e:any){setError(e.message)}})()},[]);if(!profile&&!error)return <main className="container"><Loading text="Loading control center…"/></main>;return <main className="container"><div className="page-header"><div><div className="muted small">CRL CONTROL CENTER</div><h1 className="page-title">Superadmin</h1></div></div>{error&&<div className="card error-card">{error}</div>}{profile&&<><section className="card profile-card"><div className="avatar">{profile.agent_name.slice(0,2).toUpperCase()}</div><div><div className="profile-name">{profile.agent_name}</div><div className="muted small">{profile.email}</div></div></section><section className="section"><div className="grid grid-4"><div className="card kpi-card"><div className="kpi-label">Agents</div><div className="kpi">{counts.agents}</div></div><div className="card kpi-card"><div className="kpi-label">Customers</div><div className="kpi">{counts.customers}</div></div><div className="card kpi-card"><div className="kpi-label">Pre-Visits</div><div className="kpi">{counts.pre}</div></div><div className="card kpi-card"><div className="kpi-label">Visits</div><div className="kpi">{counts.visits}</div></div></div></section><section className="section card"><h2 className="section-title">Management</h2><div className="actions"><Link className="btn" href="/superadmin/agents">Manage Agents</Link><Link className="btn secondary" href="/superadmin/customers">Manage Customers</Link><Link className="btn secondary" href="/superadmin/pre-visits">Manage Pre-Visits</Link><Link className="btn secondary" href="/superadmin/visits">Manage Visits</Link></div></section></>}</main>}
