drop policy if exists "agents see today's assigned customers; admins see all" on public.customers;
drop policy if exists "agents see assigned customers; admins see all" on public.customers;
drop policy if exists "customer select access" on public.customers;

create policy "agents see assigned customers; admins see all"
on public.customers
for select
to authenticated
using (
  public.current_role() = any (array['admin'::text, 'superadmin'::text])
  or lower(agent_email) = lower(public.current_email())
);

create table if not exists public.agent_attendance (
  attendance_id bigint generated by default as identity primary key,
  agent_email text not null references public.agents(email) on update cascade,
  attendance_date date not null default current_date,
  check_in_at timestamptz not null default now(),
  check_in_latitude double precision,
  check_in_longitude double precision,
  check_in_accuracy_m double precision,
  check_out_at timestamptz,
  check_out_latitude double precision,
  check_out_longitude double precision,
  check_out_accuracy_m double precision,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (agent_email, attendance_date)
);

alter table public.agent_attendance enable row level security;

drop policy if exists "agents read own attendance; admins read all" on public.agent_attendance;
create policy "agents read own attendance; admins read all"
on public.agent_attendance
for select
to authenticated
using (
  lower(agent_email) = lower(public.current_email())
  or public.current_role() = any (array['admin'::text, 'superadmin'::text])
);

create or replace function public.agent_check_in(
  p_latitude double precision default null,
  p_longitude double precision default null,
  p_accuracy_m double precision default null
)
returns public.agent_attendance
language plpgsql
security definer
set search_path = public
as $$
declare
  v_email text := lower(public.current_email());
  v_row public.agent_attendance;
begin
  if v_email is null or v_email = '' then raise exception 'Not authenticated'; end if;
  if public.current_role() <> 'agent' then raise exception 'Only agents can check in'; end if;
  insert into public.agent_attendance (agent_email, attendance_date, check_in_at, check_in_latitude, check_in_longitude, check_in_accuracy_m)
  values (v_email, current_date, now(), p_latitude, p_longitude, p_accuracy_m)
  on conflict (agent_email, attendance_date)
  do update set
    check_in_latitude = coalesce(public.agent_attendance.check_in_latitude, excluded.check_in_latitude),
    check_in_longitude = coalesce(public.agent_attendance.check_in_longitude, excluded.check_in_longitude),
    check_in_accuracy_m = coalesce(public.agent_attendance.check_in_accuracy_m, excluded.check_in_accuracy_m),
    updated_at = now()
  returning * into v_row;
  return v_row;
end;
$$;

create or replace function public.agent_check_out(
  p_latitude double precision default null,
  p_longitude double precision default null,
  p_accuracy_m double precision default null
)
returns public.agent_attendance
language plpgsql
security definer
set search_path = public
as $$
declare
  v_email text := lower(public.current_email());
  v_row public.agent_attendance;
begin
  if v_email is null or v_email = '' then raise exception 'Not authenticated'; end if;
  if public.current_role() <> 'agent' then raise exception 'Only agents can check out'; end if;
  update public.agent_attendance
  set check_out_at = now(),
      check_out_latitude = p_latitude,
      check_out_longitude = p_longitude,
      check_out_accuracy_m = p_accuracy_m,
      updated_at = now()
  where lower(agent_email) = v_email
    and attendance_date = current_date
    and check_out_at is null
  returning * into v_row;
  if v_row.attendance_id is null then raise exception 'Check in first before checking out'; end if;
  return v_row;
end;
$$;

grant execute on function public.agent_check_in(double precision,double precision,double precision) to authenticated;
grant execute on function public.agent_check_out(double precision,double precision,double precision) to authenticated;
